### ISSUE TITLE
Could NOT find liblcf (missing: LIBLCF_LIBRARY LIBLCF_INCLUDE_DIR) (found   version "0.5.4")

### ISSUE THREAD

**Issue by LucasMW** [EasyRPG/Editor-Qt#122]
```
Could NOT find liblcf (missing: LIBLCF_LIBRARY LIBLCF_INCLUDE_DIR) (found
  version "0.5.4")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /Users/lmenezes/Cloned_From_Github/easyRPG/liblcf/builds/liblcf-config.cmake:57 (find_package_handle_standard_args)
  CMakeLists.txt:146 (find_package)
```

**Comment by LucasMW** [comment]
Attempted on Mac OS High Sierra

**Comment by LucasMW** [comment]
This is the result of 
     $ cmake .

liblcf was built from git

**Comment by carstene1ns** [comment]
Did you just build liblcf (i.e. no installation)?, because it seems to me that the path to the config file is from the git checkout, not installation folder.
Also, how did you setup the paths?

**Comment by LucasMW** [comment]
At liblcf directory the step 'sudo make install' fails

**Comment by carstene1ns** [comment]
You do not need to install it system-wide, you can also do locally (with "prefix").
Just needs to set the same path for Editor build then.

**Comment by carstene1ns** [comment]
You need to use `-DCMAKE_INSTALL_PREFIX=<path>`. In the following asciicast I built a static liblcf, so I do not need to mess with shared library load paths afterwards (`-DBUILD_SHARED_LIBS=OFF`).
Important is that the Editor build finds liblcf in the right location
(in my case `-- Found liblcf: /tmp/easyrpg/lib64/liblcf.a (found version "0.5.4")`.

[![asciicast](https://asciinema.org/a/JFzRzCGNNS3iSvVgSwG10RoP7.svg)](https://asciinema.org/a/JFzRzCGNNS3iSvVgSwG10RoP7)

**Comment by carstene1ns** [comment]
Question is, where does `tmp/easyrpg/lib` come from? Note that I used `/tmp` folder in my asciicast as arbitrary directory, which you likely should replace with your `/Users/lmenezes/Cloned_From_Github/easyRPG/` folder.

Clean your cmake caches in every project and try again:
```bash
rm -rf CMakeFiles
rm -f CMakeCache.txt
```

I still think you are doing something wrong, but I cannot guess. It is really not easy to help you when you only provide small bits of information. Would be good when you provide the exact commands you enter.

**Comment by LucasMW** [comment]
`[100%] Built target EasyRPG_Editor_exe`
Thank you, now it worked. 
It appears I had bad configuration leftovers from in my cmake files.
Cleaning it with 
rm -rf CMakeFiles
rm -f CMakeCache.txt 
helped a lot.

**Comment by carstene1ns** [comment]
Great that you got it to work. Closing then.
