### ISSUE TITLE
macOS: Add AppBundle support

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Editor-Qt#141]
The CMakeLists lacks App bundle support.
Also there is no suitable icon and no suitable plist file.

@tyrone-sudeium can you help? :)

For "macqtdeploy" see https://stackoverflow.com/questions/51556088/cmake-copy-dependencies-to-executable-output-path/51569345 (tested it, works)

**Comment by tyrone-sudeium** [comment]
Will check it out this weekend if I get time :)

**Comment by Ghabry** [comment]
Oh and please set the "Retina support" flag. High DPI support is essential (though I will use Windows when fixing DPI issues, shouldn't make a huge difference because it is Qt ;))
