### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by xiaoyilong19** [EasyRPG/Editor-Qt#68]
why I can't find the file which name is " rpg_map.h" and "data.h"

**Comment by fdelapena** [comment]
Hello xiaoylon19, these files are from "liblcf", which it is a dependency.
Which operating system are you using for building Editor-Qt?
We need to improve Editor-Qt building documentation.

**Comment by LatticeWu** [comment]
Hi fdelapena, I tried to build this project, but can not found file 'sicudtd.lib'. I searched the disk, only can found 'icudt.lib'. expat, icu and liblcf are already installed. I got the icu from internet, maybe something wrong with the version. Can you tell me where can get the correct one? Operating system is windows 8, 64bit, environment is visual studio 2012 and Qt 5.2.0. Waiting for your help, thanks so much.

**Comment by fdelapena** [comment]
Hi LatticeWu, the last "d" before .lib is the "debug" version. You can try to edit the EasyRPG-Editor.pro file to remove the d or build in release mode.
