### ISSUE TITLE
Editor generates a dummy .emt file in the games path folder when closing a project

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Editor-Qt#72]
It should not create this file.

**Comment by MarianoGnu** [comment]
emt is the extention for "easy map tree" file (rm's lmt file extention)
Why do you say i'ts a dummy? does it create 2 files?

**Comment by fdelapena** [comment]
It creates a valid xml file without the map tree structure but without maps defined.
Open the template project, close the project and the file will be generated in the bin folder (because this is the current game base folder containing game subfolders, i.e. "template").

**Comment by MarianoGnu** [comment]
Hum, now you mention it, we should't be able to "open" template projects, they are only for cloning, maybe we should change extensions for templates and maybe even using binary for those. Btw what version are you using? #70 is not ready to merge yet and wont work at all like before.
Anyway my lastest tests loaded the map tree correctly, this needs some test... maybe a regresion introduced in #71? :/

**Comment by fdelapena** [comment]
> Anyway my lastest tests loaded the map tree correctly, this needs some test... maybe a regresion introduced in #71? :/

The map loads properly, it just generates a dummy lmt where it should not generate any file because we just are closing the project without saving.

Well, about a possible regression, maybe https://github.com/EasyRPG/Editor-Qt/pull/71/files#diff-585cfecf0ce15ac75be3038e77e65611R1238 is related. I'm using upstream master, not your branch.

**Comment by Ghabry** [comment]
Should be fixed by #125 which properly handles legacy and easyrpg project loading and saving.

**Comment by carstene1ns** [comment]
Has this been verified yet?

**Comment by Ghabry** [comment]
this is solved, there is now proper Save management now depending on the project type (legacy vs easy)
