### ISSUE TITLE
RFC: Consider Qt Quick + Qml?

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Editor-Qt#76]
Qt Widgets are consideres as outdated since Qt 5 and don't really receive updates anymore, besides bugfixes.

The new hot shit since Qt 5 is QtQuick + Qml which is a declarative Ui language. Gives some nice features like e.g. data binding without writing any C++ code, saves repetitive code and makes it easier to create custom Ui elements if necessary.

Native UI elements are available: https://doc.qt.io/qt-5/qtquickcontrols-overview.html

Can't be that bad because KDE 5 migrates currently everything to Qml.

Just mentioning this because our editor is not that advanced yet from a GUI perspective, so it's not too late to discuss this.

**Comment by MarianoGnu** [comment]
I thought QtQuick was for phone apps...

**Comment by fdelapena** [comment]
> What about lisence? Qt is every time more restrictive imo :( damn Microsoft

Qt licensing is "[okay](https://doc.qt.io/qt-5/licensing.html)". The only "issue" is the copyright holding, but a minor one really. Qt developers need to sign a contribution agreement but this happens with a lot of free/open source software. A fork can be made in any moment if they try to do nasty things when this happens (e.g. Oracle with OpenOffice -> Libreoffice; MySQL -> MariaDB, etc.).

By the way, wxWidgets has a more [liberal license](http://www.wxwidgets.org/about/licence/) than Qt. It is a modified LGPL2+ which allows to be used in modified software in binary form with own terms, making it compatible with GPL and commercial programs even with static linking or library modifications ([remarks](https://wiki.wxwidgets.org/License_Gotchas)).

**Comment by Ghabry** [comment]
@MarianoGnu 
Correct the initial version of QtQuick was targeting phone only. But the newer also feature desktop widgets.
That's why I think it is worth a look.

**Comment by MarianoGnu** [comment]
I meant the "buy me if you want upgrades" thing :tongue:

**Comment by fmatthew5876** [comment]
I'm still brushing up on QT so my opinion may change later. For now I would stick with C++ widgets. It'll interact with our C++ liblcf easier.

C++ widgets will be around forever. Qml/QtQuick could be hot today and then left unsupported later when the new hotness arrives.

I'm not sure Editor on mobile would ever make sense, would it?

**Comment by fdelapena** [comment]
Qt Quick 1 has been deprecated in just 3 years and the whole module will be removed some day. Qt Quick 2 drops native widgets support and a lot of useful stuff, e.g. the toolbar needs to be designed mostly handmade because by default uses the triple dot button (burger-like dropdown menu).

Because it is focused for mobile and Qt Widgets are still available for mobile if really needed and they are supported long term, I guess we may stick to Qt Widgets.

**Comment by MarianoGnu** [comment]
Yeah, Qt deprecates APIs so ofter, it doesnt make sense to swirch tecnology imo
