### ISSUE TITLE
How to install on ubuntu?

### ISSUE THREAD

**Issue by kholyphoenix1** [EasyRPG/Editor-Qt#82]
Hello, 

How install on Ubuntu?
I'm confused.

Thanks a lot!

**Comment by Zegeri** [comment]
Sorry, but this isn't ready for use yet and there haven't been any releases.

**Comment by kholyphoenix1** [comment]
only available to developers? No release date for use?

**Comment by Ghabry** [comment]
You can compile it from source but this is by far not in a usable state for end users. Basicly the only things working are importing RPG2k/2k3 projects and the map rendering. I'm one of the EasyRPG developers and not even I use this program in it's current state.

**Comment by kholyphoenix1** [comment]
Ghabry, thanks!!!

**Comment by MarianoGnu** [comment]
Also map edition and edit HEROES database page, but that's all

**Comment by kholyphoenix1** [comment]
The program does not run the game yet?

**Comment by Ghabry** [comment]
If you want to run games use https://github.com/EasyRPG/Player/

**Comment by kholyphoenix1** [comment]
I understand. Thanks a lot!

**Comment by fdelapena** [comment]
Editor-Qt was not building until yesterday, but got fixed. If you still want to build it on Ubuntu:

First, install liblcf by following this guide:

https://wiki.easyrpg.org/development/compiling/liblcf/autotools#step-by-step-setup-for-debian-based-distros-gnewsense-trisquel-debian-mint-ubuntu

Then, install Qt dependencies, download Editor-Qt, build and run with these steps:

    sudo apt -y install qt5-default qtmultimedia5-dev
    git clone https://github.com/EasyRPG/Editor-Qt.git
    cd Editor-Qt
    qmake
    make
    cd bin
    ./easyrpg-editor

**Comment by kholyphoenix1** [comment]
Thank you for the clarification!

**Comment by kholyphoenix1** [comment]
fdelapena, 

I can not install the libscf.

shell: 
/home/bethe/Downloads/Editor-Qt/liblcf# ./configure --prefix -usr
bash: ./configure: File or directory not found

**Comment by carstene1ns** [comment]
Did you run `autoreconf -i` ? It will create the `configure` file.

**Comment by kholyphoenix1** [comment]
root@jr-desktop:/home/bethe/Downloads/Editor-Qt/liblcf# autoconf -i
configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:9: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:10: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:18: error: possibly undefined macro: AM_PROG_AR
configure.ac:26: error: possibly undefined macro: AC_DEFINE
root@jr-desktop:/home/bethe/Downloads/Editor-Qt/liblcf#

**Comment by carstene1ns** [comment]
`autoconf` != `autoreconf`.

What `autoreconf` does is in detail:
`aclocal && autoheader && automake --foreign --add-missing && autoconf`

**Comment by kholyphoenix1** [comment]
It worked!

autoreconf -i && ./configure 

---

Erro...


checking for ICU... no
configure: error: Package requirements ( icu-i18n) were not met:

No package 'icu-i18n' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ICU_CFLAGS
and ICU_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by carstene1ns** [comment]
Sorry, seems the wiki page still misses the ICU dependency.
You need to install it, i.e. `# apt-get install libicu-dev`

**Comment by kholyphoenix1** [comment]
**Solved with** apt-get install libicu-dev 

Now...
configure: error: Package requirements ( expat >= 2.1) were not met:
No package 'expat' found

I try install...
With: apt-get install expat...

**Comment by carstene1ns** [comment]
Looking at the Wiki page again, I see it lists `libicu-dev` and `libexpat1-dev` correctly as dependencies, it is just not visible without scrolling to the right.

**Comment by kholyphoenix1** [comment]
Ok, thanks!

**Comment by fdelapena** [comment]
> I concluded what I do now? Finish compiled liblcf...

Then as mentioned above, just continue with the Editor-Qt setup. But once built, don't expect a stable or usable product. Existing crashes and issues are well known to happen.

**Comment by kholyphoenix1** [comment]
I understand. Thanks for informing

**Comment by Ghabry** [comment]
@kholyphoenix1 
Did you solve this?

**Comment by kholyphoenix1** [comment]
Thanks,
Solved.
