### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by x86poem** [EasyRPG/Editor-Qt#84]
hello, 
while I try to download binary, 
I found following link broken from https://github.com/EasyRPG/Editor-Qt/tree/master/bin/templates

https://easy-rpg.org/jenkins/job/player-win32-editor-support/lastSuccessfulBuild/artifact/bin/easyrpg_windows.zip

**Comment by Ghabry** [comment]
Where did you find these links?

**Comment by x86poem** [comment]
I found the broken link from 
https://github.com/EasyRPG/Editor-Qt/blob/master/bin/templates/README
