### ISSUE TITLE
Overlay for QGraphicsMapScene

### ISSUE THREAD

**Issue by punkkeks** [EasyRPG/Editor-Qt#92]
I want some kind of overlay where some basic (important) information are shown, e.g. X/Y coordination, event-name (if any is below cursor) and some other data I don't know yet.
It should look something like [this](http://wiki.altium.com/download/attachments/37613723/Designator_comment_uebertragen.jpg?version=1&modificationDate=1338910737050). It could be more transparent and/or should change it's location from the upper left side to the upper right side, if the mouse is somewhere near the overlay, so it doesn't bother the builder/creator/whoever.

I open this issue, because I don't know how the drawing in Qt works, and so I can't get it working. If someone is willing to give me a hint, I would provide a basic implementation (or the person just could write it :P )

**Comment by Ghabry** [comment]
How about placing this in the status bar like most graphic programs do?

![screenshot_20160915_161214](https://cloud.githubusercontent.com/assets/1331889/18553009/352b812e-7b5f-11e6-9d2d-518aed7378f9.png)

**Comment by punkkeks** [comment]
I tried that at first, but the problem was, that I couldn't get a reference to the mainwindow (I don't know how many parent() calls I tried) If you have a proper solution for that, why not ;)

**Comment by MarianoGnu** [comment]
use an static var to store a reference of the main window (a singleton)

**Comment by punkkeks** [comment]
Nah... I don't like singletons that much, although when you use it for the **main**window I think it would be okay, but Ghabry already solved this ;)

**Comment by Ghabry** [comment]
I planned a singleton first but this breaks when detaching of map tabs in windows with there own status bar happens.

That's not implemented just feature proof ;)
