### ISSUE TITLE
Included templates are no longer readable by liblcf

### ISSUE THREAD

**Issue by rohkea** [EasyRPG/Editor-Qt#99]
Editor-Qt includes Template fields that are copiable to each new project. The templates use XML format, but the XML format of liblcf changed and it can no longer parse the old format (it contains fields like ``pdef_f``, ``mdef_f``, ``unknown_03`` and some more). Because of this, Editor-Qt segfaults when creating or opening a project.

As a temporary workaround, converting RM2k database file into .xml with lcf2xml, and copying this file into bin/templates/EASY_RT.edb (overwriting the previous content) works.

This might be related to https://github.com/EasyRPG/Editor-Qt/issues/98

**Comment by carstene1ns** [comment]
Fixed by #100.
